services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapizada
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
  
  python:
    container_name: python_container
    image: python:3.11
    volumes:
      - .:/src:ro
    working_dir: /src
    command: bash -c "pip install -r ./requirements.txt && python -m uvicorn main:app --host 0.0.0.0"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapizada
      - POSTGRES_HOST=postgres #referencia ao serviço postgres
      - POSTGRES_PORT=5432
    ports:
      - 8000:8000
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:

volumes:
    postgres: